name: fake_review_creator
description: "Fake review creator written in flutter."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  dynamic_color: ^1.7.0
  flutter:
    sdk: flutter
  html: ^0.15.4
  http: ^1.2.2
  path_provider: ^2.1.4
  sanitize_filename: ^1.0.5
  shared_preferences: ^2.3.2
  webdriver: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true